version: '3.8'
services:
  trademarksearchservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - INIT_TRADE_MARK_URL=init
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: searching_trademark_test_db
    volumes:
      - ./infastructure/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
